// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0O89f6Uwr1gK5nkEDDjPSYQQrYIuSR3U',
    appId: '1:579073175720:web:61f4f2c492838c6aadd29d',
    messagingSenderId: '579073175720',
    projectId: 'flutter-ernar',
    authDomain: 'flutter-ernar.firebaseapp.com',
    storageBucket: 'flutter-ernar.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVcvldf9M52ez8QzRuuwZzACPF7yLjvlE',
    appId: '1:579073175720:ios:44c909266836779eadd29d',
    messagingSenderId: '579073175720',
    projectId: 'flutter-ernar',
    storageBucket: 'flutter-ernar.firebasestorage.app',
    iosBundleId: 'com.example.classroomInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0O89f6Uwr1gK5nkEDDjPSYQQrYIuSR3U',
    appId: '1:579073175720:web:46e6b69118f557a0add29d',
    messagingSenderId: '579073175720',
    projectId: 'flutter-ernar',
    authDomain: 'flutter-ernar.firebaseapp.com',
    storageBucket: 'flutter-ernar.firebasestorage.app',
  );
}
